# Generated by Django 3.0.3 on 2020-02-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcorder',
            old_name='product',
            new_name='fcproduct',
        ),
    ]
